version: '3.8'
services:
  # Django app
  backend_cryptocurrency:
    container_name: boomslag_ms_cryptocurrency
    build: .
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8020"
    volumes:
      - .:/app
    ports:
      - 8020:8020
    depends_on:
      - db_cryptocurrency
      - redis
  # Event Queue Kafka
  queue_cryptocurrency:
    build: .
    command: >
      sh -c "python consumer.py"
    depends_on:
      - db_cryptocurrency
  # Database (PostgreSQL)
  db_cryptocurrency:
    image: postgres
    container_name: django_cryptocurrency_api_postgresql
    restart: always
    environment:
      POSTGRES_DB: boomslag_cryptocurrency_db
      POSTGRES_USER: boomslag
      POSTGRES_PASSWORD: postgres
    ports:
      - 5452:5432
    volumes:
      - .dbdata:/var/lib/postgresql
  # Redis Cache
  redis:
    image: redis
    container_name: django_cryptocurrency_api_redis
    ports:
      - 6349:6379